### PR TITLE
Create GitHub Actions workflow for JavaScript CI

### PR DESCRIPTION
**Pull request by ScottBrenner**
# Summary

Creating a GitHub Actions workflow for Node.js CI.

# Details

This workflow is copied from [GitHub's starter workflows repository](https://github.com/actions/starter-workflows/blob/master/ci/node.js.yml). Sounds like the frontend will be using some flavor of Node.js, can be adapted as needed.

Reference - https://github.com/features/actions

_closes #2 ?_

Note: GitHub Actions must be enabled in this repository for the workflow to run
image

### CODE REVIEW

**Comment by 839083** [comment]
Probably React but LGTM. Not sure who can approve PRs

**Comment by gooftroop** [comment]
I'm unfamiliar with GitHub actions. How does it compare to the functionality not Travis ci or circleci? Namely can GitHub actions run jobs conditionally based on the presence of a tag or a merge request against master?

**Comment by ScottBrenner** [comment]
> can GitHub actions run jobs conditionally based on the presence of a tag or a merge request against master?

Yes, see https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#onpushpull_requestbranchestags for reference.

**Comment by gooftroop** [comment]
Another requirement for our build system may be to build two bundles - one that's es6 and one that's es5 to support legacy and modern browsers. Travis and circleci has the ability to run a matrix or jobs based on variables - without having read too much of the documentation due to time constraints right now, do you know if github actions can do similar or satisfy that requirement?

**Comment by ScottBrenner** [comment]
Yes, GitHub Actions has extensive support for build matrices - https://help.github.com/en/articles/workflow-syntax-for-github-actions#jobsjob_idstrategymatrix

**Comment by gooftroop** [comment]
Did some more reading - github actions looks like a solid choice. Were you planning on updating it to be specific for our app?

**Comment by ScottBrenner** [comment]
Happy to adapt as needed - feel free to commit into this branch as well - but I don't know what a workflow specific to this app would look like.

**Comment by gooftroop** [comment]
More than happy to contribute to this branch, but unfortunately it's a fork from your repo. Are you able to convert/recreate it as a feature branch? If not that's fine - honestly the initial commit of this doesn't have to be complicated. At minimum all we'd want to do is:

1. install npm modules
2. run lint via `npm run lint`
3. run tests va `npm test`
4. run the build via `npm run build`

That should get us something basic with small value that we can build on. Don't think we'd need the matrix right now either. Since this project is just a plain JS repo and not node, you can also drop the nodeJs actions altogether too

**Comment by ScottBrenner** [comment]
Cool, will amend later today!

**Pull request closed without merging**
