### PR TITLE
Infrastructure - Serverless Framework

### PR DESCRIPTION
**Pull request by ScottBrenner**
# Summary

Proposing an infrastructure created using [the Serverless Framework's  Website Component](https://github.com/serverless/components/tree/master/templates/website). It uses AWS S3 for hosting and AWS Cloudfront for a blazing fast CDN!

# Details

Files here were generated using [serverless/components - Deploy A Website](https://github.com/serverless/components?files=1#deploy-a-website), notably creating a React application under `src/` which can be modified accordingly.

### CODE REVIEW

**Comment by gooftroop** [comment]
How would this integrate with the proposed GitHub actions?

**Comment by ScottBrenner** [comment]
The proposed action is for continuous integration, unrelated to what's happening here.  https://github.com/serverless/github-action can be used for continuous deployment to the infrastructure proposed here.

**Comment by gooftroop** [comment]
How does your solution compare to other alternatives? Why would you prefer this over others?

**Comment by ScottBrenner** [comment]
https://serverless.com/learn/comparisons/

What other alternatives?

**Comment by gooftroop** [comment]
A common practice is to use the CI/CD jobs to build and deploy an app. Many companies use terraform or cloudformation for infrastructure-as-code. The comparisons sheet you linked is interesting, but I was hoping to hear more about your own personal experiences with this solution, how it compares to others you may have used, and why you would recommend serverless

**Comment by chmccc** [comment]
@gooftroop just to throw this in, there's not necessarily a conflict between this and pipeline tools like you mentioned: https://serverless.com/blog/ci-cd-workflow-serverless-apps-with-circleci/

**Comment by gooftroop** [comment]
This PR will act as an integration branch and we'll merge PRs into it to bring it up-to-date with our React and coding standards. Once those PRs are merged in we'll merge this to master

**Comment by gooftroop** [comment]
This fork has been subsumed by https://github.com/openventilatorregistry/Frontend/pull/12, which is a feature branch and has all the code in this fork. @ScottBrenner can you close this and verify the feature branch has all your changes?

**Pull request closed without merging**
